#!/bin/sh

type=3xN_CORR+soil_ferti_OPER
cp SOIL.SOL_exp_ferti_sol SOIL.SOL
cp SOIL.SOL_exp_ferti_sol soil.sol

period=1
###############
d0=myd0
ddatain0=myddatain0
dout0=mtdout0
mkdir -p ${dout0}

faxtempl=FIFU9901.MZX_work_${type}
fax=FIFU9901.MZX

for model in  CNR-CLM CNR-RACMO ICH-RACMO NCC-HIRH NCC-REMO \
              CNRM-CERFACS-CNRM-CM5-SMHI-RCA4 ICHEC-EC-EARTH-SMHI-RCA4 MPI-M-MPI-ESM-LR-SMHI-RCA4 ; do

#scen=historical
#scen=rcp45
scen=rcp85
part=1
#####################################

case ${scen} in \
 Ctrl) clscen=MARS ;clscen4=MARS;
        if [ ${part} -eq 1 ] ; then
         yst=1976
         yen=2005
        fi;;
 historical) clscen=HIST ;clscen4=HIST;
        if [ ${part} -eq 1 ] ; then
         yst=1976
         yen=2005
        fi;;
 rcp45) clscen=RCP45 ;clscen4=RCP4;
        if [ ${part} -eq 1 ] ; then
         yst=2021
         yen=2050
        else 
         yst=2070
         yen=2099
        fi ;; 
 rcp85) clscen=RCP85 ;clscen4=RCP8;
        if [ ${part} -eq 1 ] ; then
         yst=2021
         yen=2050
        else 
         yst=2070
         yen=2099
        fi ;; 
esac

#echo "yst, yen=" ${yst} ${yen}

dexp00=Res_${type}
dexp0=${dexp00}/${model}
exp0=${dexp0}/${scen}
mkdir -p ${exp0}
 
ddatain=${ddatain0}/${scen}/Input_DSSAT/${model}
echo "ddatain=" ${ddatain}

cd ${d0}
mkdir -p old_tmp
mv ${clscen}*.WTH old_tmp
mv ${clscen4}*.WTH old_tmp

cp ${ddatain}/${clscen}*.WTH .

ys=${yst}
ye=${yen}

yy=${ys}
while [ ${yy} -le ${ye} ] ; do 
yy2t=`expr ${yy} | cut -c 3-4 `
yy2=`expr ${yy2t} + 100 | cut -c 2-3 `
echo "YEAR=" ${yy2}

fawin=${clscen}${yy}01.WTH
fawinl=${clscen4}${yy2}01.WTH
mv ${fawin} ${fawinl}

#echo "fawin=" ${fawin}
dout=${dout0}/${exp0}/YY_${yy}
mkdir -p ${dout}
\rm fin_tmp* ${fax}


#for plday in '091' '101' '120' '135' ; do
plday1='091'
plday2='101'
plday3='120'
plday4='135'

## harvest date
/usr/bin/sed -e "1,\$s/1 95304/1 ${yy2}304/g" < ${d0}/${faxtempl} > fin_tmp1
## irrigation date
/usr/bin/sed -e "1,\$s/1 95115/1 ${yy2}115/g" <  fin_tmp1 > fin_tmp2
## planting date date
/usr/bin/sed -e "1,\$s/1 95${plday1}/1 ${yy2}${plday1}/g" <  fin_tmp2 > fin_tmp3
/usr/bin/sed -e "1,\$s/2 95${plday2}/2 ${yy2}${plday2}/g" <  fin_tmp3 > fin_tmp4
/usr/bin/sed -e "1,\$s/3 95${plday3}/3 ${yy2}${plday3}/g" <  fin_tmp4 > fin_tmp5
/usr/bin/sed -e "1,\$s/4 95${plday4}/4 ${yy2}${plday4}/g" <  fin_tmp5 > fin_tmp6
# harvest last
/usr/bin/sed -e "1,\$s/95334/${yy2}334/g" <  fin_tmp6 > fin_tmp7
# Wather file scen
/usr/bin/sed -e "1,\$s/MARS/${clscen4}/g" <  fin_tmp7 > fin_tmp8
## start   date date
/usr/bin/sed -e "1,\$s/GE              1     1     S 95001/GE              ${period}     1     S ${yy2}001/g" <  fin_tmp8 > ${fax}

#echo done, planting day loop, pday=' ${plday}
#done

###########################################################

fawinl=${clscen4}${yy2}01.WTH

./dscm048_fin_teste_14apr2022 A ${fax} NA 1>o1_${yy} 2>o2_${yy}
mv *OUT ${dout}
mv ${fax} ${dout}
mv o1_${yy} o2_${yy} ${dout}

echo "DONE, year loop=" ${yy}
yy=`expr ${yy} + 1 `
done

echo "DONE, model=" ${model}
done

#########################################################################
#########################################################################
